In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df = pd.read_csv('covid_toy.csv')

In [5]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [6]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [7]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                    test_size=0.2)

In [11]:
X_train

    age  gender  fever   cough       city
52   47  Female  100.0  Strong  Bangalore
63   10    Male  100.0    Mild  Bangalore
78   11    Male  100.0    Mild  Bangalore
41   82    Male    NaN    Mild    Kolkata
24   13  Female  100.0  Strong    Kolkata
..  ...     ...    ...     ...        ...
4    65  Female  101.0    Mild     Mumbai
53   83    Male   98.0    Mild      Delhi
19   42  Female    NaN  Strong  Bangalore
83   17  Female  104.0    Mild    Kolkata
44   20    Male  102.0  Strong      Delhi

[80 rows x 5 columns]

### 1. Aam Zindagi

In [12]:
si = SimpleImputer()