In [12]:
import numpy as np
import pandas as pd

In [13]:
df = pd.read_csv('customer.csv')

In [14]:
df.sample(5)

    age  gender   review education purchased
9    74    Male     Good        UG       Yes
18   19    Male     Good    School        No
31   22  Female     Poor    School       Yes
28   48    Male     Poor    School        No
34   86    Male  Average    School        No

In [15]:
df = df.iloc[:,2 :]

In [16]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No